### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by CW-Jesse** [KPro1982/TeleportEverything#31]
Thank you for your excellent mod!

On my private server, TeleportEverything was responsible for about 50% of the main thread processing time for my users.

Seem to be due to calling IsAreaReady every frame here:

https://github.com/KPro1982/TeleportEverything/blob/5de482aded84232cacc88a111cbdf956509e5bd5/TeleportEverything/HarmonyPatches.cs#L231

If it's only necessary to know the result of that when teleporting, then bringing IsAreaReady down to:

`(!___m_teleporting && TeleportTriggered && ZNetScene.instance.IsAreaReady(this.m_teleportTargetPos))`

should fix it, **assuming IsAreaReady doesn't need to be called every frame**; I'm not as familiar with the teleportation system.

**Comment by elgthedev** [comment]
Good catch, I didn't think about this when I was creating this method. 
I've just released it (v2.3.1), this should increase a lot the performance. 
Thanks again.
